//
//  MoveAction.swift
//  swift-2048
//
//  Created by qbuser on 27/02/23.
//

import Foundation

// These actions will be generated by the Alogirthm and move all the way to the view so the changes can be properly animated.
enum MoveAction<T: Evolvable>: CustomStringConvertible {
    case Spawn(tile: Tile<T>) // Spawns a new tile
    case Move(from: Coordinate, to: Coordinate) // Moves a tile
    case Merge(from: Coordinate, andFrom: Coordinate, toTile: Tile<T>) // Merge two tiles
    
    var description: String {
        get {
            switch self {
            case let .Spawn(gamePiece):
                return "Spawn(gamePiece: \(gamePiece)"
            case let .Move(from, to):
                return "Move(from: \(from), to: \(to))"
            case let .Merge(from, to, toGamePiece):
                return "Merge(from: \(from), and: \(to), toGamePiece: \(toGamePiece))"
            }
        }
    }
}
